# coding: utf-8
module CdnProvince
  def canonicalize_province(name)
    case name.downcase
    when 'ab'
      'AB'
    when 'alberta'
      'AB'
    when 'bc'
      'BC'
    when 'british columbia'
      'BC'
    when 'colombie britannique'
      'BC'
    when 'pq'
      'QC'
    when 'qc'
      'QC'
    when 'québec'
      'QC'
    when 'quebec'
      'QC'
    when 'on'
      'ON'
    when 'ontario'
      'ON'
    when 'sk'
      'SK'
    when 'saskatchewan'
      'SK'
    when 'manitoba'
      'MB'
    when 'mb'
      'MB'
    when 'nb'
      'NB'
    when 'new brunswick'
      'NB'
    when 'nouveau brunswick'
      'NB'
    when 'pe'
      'PE'
    when 'prince edward island'
      'PE'
    when 'pei'
      'PE'
    when 'nf'
      'NF'
    when 'newfoundland'
      'NF'
    when 'nv'
      'NV'
    when 'nunavut'
      'NV'
    when 'northwest territories'
      'NT'
    when 'yk'
      'YK'
    when 'yukon'
      'YK'
    when 'terre neuve'
      'NF'
    when 'nova scotia'
      'NS'
    when 'nouvelle ecosse'
      'NS'
    end
  end
end



