# coding: utf-8
module CdnProvince
  def canonicalize_province(name)
    case name.downcase
    when 'ab'
      'AB'
    when 'alberta'
      'AB'
    when 'bc'
      'BC'
    when 'british columbia'
      'BC'
    when 'colombie britannique'
      'BC'
    when 'pq'
      'QC'
    when 'qc'
      'QC'
    when 'québec'
      'QC'
    when 'quebec'
      'QC'
    when 'on'
      'ON'
    when 'ontario'
      'ON'
    when 'sk'
      'SK'
    when 'saskatchewan'
      'SK'
    when 'manitoba'
      'MB'
    when 'mb'
      'MB'
    when 'nb'
      'NB'
    when 'new brunswick'
      'NB'
    when 'nouveau brunswick'
      'NB'
    when 'pe'
      'PE'
    when 'île-du-prince-édouard'
      'PE'
    when 'ile-du-prince-edouard'
      'PE'
    when 'île du prince édouard'
      'PE'
    when 'ile du prince edouard'
      'PE'
    when 'prince edward island'
      'PE'
    when 'pei'
      'PE'
    when 'nl'
      'NL'
    when 'nf'
      'NL'
    when 'newfoundland'
      'NL'
    when 'terre neuve'
      'NL'
    when 'terre-neuve-et-labrador'
      'NL'
    when 'terre neuve et labrador'
      'NL'
    when 'labrador'
      'NL'
    when 'nv'
      'NU'
    when 'nu'
      'NU'
    when 'nunavut'
      'NU'
    when 'northwest territories'
      'NT'
    when 'territoires du nord-ouest'
      'NT'
    when 'territoires du nord ouest'
      'NT'
    when 'yk'
      'YK'
    when 'yukon'
      'YK'
    when 'nova scotia'
      'NS'
    when 'nouvelle-écosse'
      'NS'
    when 'nouvelle écosse'
      'NS'
    when 'nouvelle ecosse'
      'NS'
    end
  end
end



